-- Add up migration script here

ALTER TABLE server ALTER COLUMN region DROP NOT NULL;
ALTER TABLE server ALTER COLUMN server DROP NOT NULL;
ALTER TABLE server ALTER COLUMN zone DROP NOT NULL;
ALTER TABLE server ALTER COLUMN os DROP NOT NULL;
