WITH tool_policy(subject, tool) AS (
    VALUES
        ('group_user', 'list_projects'),
        ('group_user', 'get_project'),
        ('group_user', 'create_project'),
        ('group_user', 'create_project_app'),
        ('group_user', 'suggest_resources'),
        ('group_user', 'list_templates'),
        ('group_user', 'validate_domain'),
        ('group_user', 'get_deployment_status'),
        ('group_user', 'start_deployment'),
        ('group_user', 'cancel_deployment'),
        ('group_user', 'list_clouds'),
        ('group_user', 'get_cloud'),
        ('group_user', 'add_cloud'),
        ('group_user', 'delete_cloud'),
        ('group_user', 'list_cloud_regions'),
        ('group_user', 'list_cloud_server_sizes'),
        ('group_user', 'list_cloud_images'),
        ('group_user', 'delete_project'),
        ('group_user', 'clone_project'),
        ('group_user', 'get_user_profile'),
        ('group_user', 'get_subscription_plan'),
        ('group_user', 'list_installations'),
        ('group_user', 'get_installation_details'),
        ('group_user', 'search_applications'),
        ('group_user', 'search_marketplace_templates'),
        ('group_user', 'get_notifications'),
        ('group_user', 'mark_notification_read'),
        ('group_user', 'mark_all_notifications_read'),
        ('group_user', 'initiate_deployment'),
        ('group_user', 'trigger_redeploy'),
        ('group_user', 'add_app_to_deployment'),
        ('group_user', 'get_container_logs'),
        ('group_user', 'get_container_health'),
        ('group_user', 'list_containers'),
        ('group_user', 'restart_container'),
        ('group_user', 'diagnose_deployment'),
        ('group_user', 'escalate_to_support'),
        ('group_user', 'get_live_chat_info'),
        ('group_user', 'stop_container'),
        ('group_user', 'start_container'),
        ('group_user', 'get_error_summary'),
        ('group_user', 'get_app_env_vars'),
        ('group_user', 'set_app_env_var'),
        ('group_user', 'delete_app_env_var'),
        ('group_user', 'get_app_config'),
        ('group_user', 'update_app_ports'),
        ('group_user', 'update_app_domain'),
        ('group_user', 'preview_install_config'),
        ('group_user', 'get_ansible_role_defaults'),
        ('group_user', 'render_ansible_template'),
        ('group_user', 'validate_stack_config'),
        ('group_user', 'discover_stack_services'),
        ('group_user', 'get_vault_config'),
        ('group_user', 'set_vault_config'),
        ('group_user', 'list_vault_configs'),
        ('group_user', 'apply_vault_config'),
        ('group_user', 'configure_proxy'),
        ('group_user', 'delete_proxy'),
        ('group_user', 'list_proxies'),
        ('group_user', 'list_project_apps'),
        ('group_user', 'get_deployment_resources'),
        ('group_user', 'list_remote_secret_targets'),
        ('group_user', 'list_remote_service_secrets'),
        ('group_user', 'get_remote_service_secret'),
        ('group_user', 'set_remote_service_secret'),
        ('group_user', 'delete_remote_service_secret'),
        ('group_user', 'get_docker_compose_yaml'),
        ('group_user', 'get_server_resources'),
        ('group_user', 'get_container_exec'),
        ('group_admin', 'admin_list_submitted_templates'),
        ('group_admin', 'admin_get_template_detail'),
        ('group_admin', 'admin_approve_template'),
        ('group_admin', 'admin_reject_template'),
        ('group_admin', 'admin_list_template_versions'),
        ('group_admin', 'admin_list_template_reviews'),
        ('group_admin', 'admin_validate_template_security'),
        ('group_user', 'list_available_roles'),
        ('group_user', 'get_role_details'),
        ('group_user', 'get_role_requirements'),
        ('group_user', 'validate_role_vars'),
        ('group_user', 'deploy_role'),
        ('group_user', 'recommend_stack_services'),
        ('group_user', 'deploy_app'),
        ('group_user', 'remove_app'),
        ('group_user', 'configure_proxy_agent'),
        ('group_user', 'get_agent_status'),
        ('group_user', 'configure_firewall'),
        ('group_user', 'list_firewall_rules'),
        ('group_user', 'configure_firewall_from_role')
)
DELETE FROM public.casbin_rule cr
USING tool_policy tp
WHERE cr.ptype = 'p'
  AND cr.v0 = tp.subject
  AND cr.v1 = '/mcp/tools/' || tp.tool
  AND cr.v2 = 'CALL'
  AND cr.v3 = ''
  AND cr.v4 = ''
  AND cr.v5 = '';
