FROM rust:1.83 AS builder

WORKDIR /app
COPY Cargo.toml Cargo.lock* ./
COPY src src
COPY templates templates
COPY static static
COPY config.json config.json
RUN cargo build --release

FROM gcr.io/distroless/cc
WORKDIR /app
COPY --from=builder /app/target/release/status /status
COPY templates templates
COPY static static
COPY config.json config.json
ENV RUST_LOG=info
EXPOSE 8080
USER 0
ENTRYPOINT ["/status", "serve", "--port", "8080", "--with-ui"]