use std::convert::TryFrom;
use std::io::{self, IsTerminal, Write};
use std::path::{Path, PathBuf};

use crate::cli::ai_client::{create_provider, ollama_complete_streaming, AiProvider};
use crate::cli::ai_scanner::{
    build_generation_request, generate_config_with_ai, strip_code_fences,
};
use crate::cli::ai_scenarios::{
    detect_website_project_kind, is_qwen_website_scenario_model, load_scenario_manifest,
    missing_required_vars, next_step_id, save_scenario_state, seed_website_scenario_state,
    ScenarioSelection, ScenarioState, WEBSITE_DEPLOY_SCENARIO,
};
use crate::cli::config_parser::{
    AiConfig, AiProviderType, AppType, ConfigBuilder, DomainConfig, ProxyConfig, ProxyType,
    ServiceDefinition, SslMode, StackerConfig,
};
use crate::cli::detector::{
    detect_workspace, DetectedComposeService, DiscoveredApp, RealFileSystem, WorkspaceDetection,
};
use crate::cli::error::CliError;
use crate::cli::generator::compose::ComposeDefinition;
use crate::cli::generator::dockerfile::DockerfileBuilder;
use crate::console::commands::cli::ai::{build_system_prompt_base, run_ai_ask_with_system_prompt};
use crate::console::commands::CallableTrait;

/// Default config filename generated by `stacker init`.
pub const DEFAULT_CONFIG_FILE: &str = "stacker.yml";

pub fn full_config_reference_example() -> &'static str {
    r#"# -----------------------------------------------------------------------------
# FULL COMMENTED REFERENCE (examples)
# Uncomment and adapt the sections you need.
# -----------------------------------------------------------------------------
# organization: "acme-inc"
# project:
#   # Optional: registered platform catalog stack code for remote cloud deploy.
#   # If omitted, remote deploy uses stack_code "custom-stack" by default.
#   identity: "your-registered-stack-code"
# env_file: ".env"
# env:
#   LOG_LEVEL: "info"
#
# app:
#   # type: static | node | python | rust | go | php | custom
#   type: "node"
#   path: "."
#   # dockerfile: "Dockerfile"
#   # image: "ghcr.io/your-org/your-image:latest"  # usually for type: custom
#   # build:
#   #   context: "."
#   #   args:
#   #     APP_ENV: "production"
#   # ports:                          # explicit port mappings (override default)
#   #   - "8080:3000"
#   # volumes:                        # volume mounts for the main app container
#   #   - "./data:/app/data"
#   #   - "app_uploads:/app/uploads"
#   # environment:                    # per-app env vars (merged with top-level env)
#   #   NODE_ENV: "production"
#   #   DATABASE_URL: "postgres://app:${DB_PASSWORD}@postgres:5432/myapp"
#
# services:
#   - name: "postgres"
#     image: "postgres:16"
#     ports: ["5432:5432"]
#     environment:
#       POSTGRES_DB: "app"
#       POSTGRES_USER: "app"
#       POSTGRES_PASSWORD: "change-me"
#     volumes:
#       - "postgres_data:/var/lib/postgresql/data"
#     depends_on: []
#
# proxy:
#   # type: none | nginx | traefik
#   type: "nginx"
#   auto_detect: true
#   domains:
#     - domain: "app.example.com"
#       # ssl: none | auto | manual
#       ssl: "auto"
#       upstream: "app:3000"
#   # config: "./nginx.conf"
#
# deploy:
#   # target: local | cloud | server
#   target: "cloud"
#   # compose_file: "docker-compose.yml"
#   cloud:
#     # provider: hetzner | digitalocean | aws | linode | vultr
#     provider: "hetzner"
#     # orchestrator: local | remote
#     orchestrator: "remote"
#     region: "nbg1"
#     size: "cpx11"
#     # install_image: "trydirect/install-service:latest" # local orchestrator only
#     # remote_payload_file: "./stacker.remote.deploy.json" # remote orchestrator request payload
#     # ssh_key: "~/.ssh/id_rsa"
#   # server:
#   #   host: "203.0.113.10"
#   #   user: "root"
#   #   port: 22
#   #   ssh_key: "~/.ssh/id_rsa"
#   # registry:                          # Docker registry credentials for private images
#   #   username: "${DOCKER_USERNAME}"
#   #   password: "${DOCKER_PASSWORD}"
#   #   server: "docker.io"  # optional, defaults to Docker Hub
#
# ai:
#   enabled: true
#   # provider: openai | anthropic | ollama | custom
#   provider: "ollama"
#   # model: "deepseek-r1:latest"
#   # api_key: "${OPENAI_API_KEY}"
#   # endpoint: "http://localhost:11434"
#   timeout: 300
#   tasks: ["dockerfile", "compose"]
#
# monitoring:
#   status_panel: true
#   # healthcheck:
#   #   endpoint: "/health"
#   #   interval: "30s"
#   # metrics:
#   #   enabled: true
#   #   telegraf: true
#
# hooks:
#   # pre_build: "./scripts/pre-build.sh"
#   # post_deploy: "./scripts/post-deploy.sh"
#   # on_failure: "./scripts/on-failure.sh"
# -----------------------------------------------------------------------------"#
}

/// `stacker init [--type static|node|python|rust|go|php] [--with-proxy] [--with-ai]`
///
/// Detects the project type in the current directory and generates
/// a `stacker.yml` configuration file with sensible defaults.
///
/// When `--with-ai` is used with an AI provider configured (via flags
/// or environment variables), Stacker scans the project deeply and
/// sends the context to the AI to generate a tailored `stacker.yml`
/// with appropriate services, proxy, monitoring, etc.
pub struct InitCommand {
    pub app_type: Option<String>,
    pub with_proxy: bool,
    pub with_ai: bool,
    pub with_cloud: bool,
    /// Override AI provider (openai, anthropic, ollama, custom)
    pub ai_provider: Option<String>,
    /// Override AI model name
    pub ai_model: Option<String>,
    /// Override AI API key
    pub ai_api_key: Option<String>,
}

impl InitCommand {
    pub fn new(
        app_type: Option<String>,
        with_proxy: bool,
        with_ai: bool,
        with_cloud: bool,
    ) -> Self {
        Self {
            app_type,
            with_proxy,
            with_ai,
            with_cloud,
            ai_provider: None,
            ai_model: None,
            ai_api_key: None,
        }
    }

    pub fn with_ai_options(
        mut self,
        provider: Option<String>,
        model: Option<String>,
        api_key: Option<String>,
    ) -> Self {
        self.ai_provider = provider;
        self.ai_model = model;
        self.ai_api_key = api_key;
        self
    }
}

/// Parse an app type string (e.g. "node", "static") into `AppType`.
fn parse_app_type(s: &str) -> Result<AppType, CliError> {
    let json = format!("\"{}\"", s.to_lowercase());
    serde_json::from_str::<AppType>(&json).map_err(|_| {
        CliError::ConfigValidation(format!(
            "Unknown app type '{}'. Valid types: static, node, python, rust, go, php, custom",
            s
        ))
    })
}

fn prompt_line(prompt: &str) -> Result<String, CliError> {
    print!("{}", prompt);
    io::stdout().flush()?;
    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    Ok(input.trim().to_string())
}

fn prompt_with_default(prompt: &str, default: &str) -> Result<String, CliError> {
    let line = prompt_line(&format!("{} [{}]: ", prompt, default))?;
    if line.is_empty() {
        Ok(default.to_string())
    } else {
        Ok(line)
    }
}

fn prompt_optional(prompt: &str, default: Option<&str>) -> Result<Option<String>, CliError> {
    let formatted = match default {
        Some(value) if !value.trim().is_empty() => format!("{} [{}]: ", prompt, value),
        _ => format!("{}: ", prompt),
    };
    let line = prompt_line(&formatted)?;
    if line.is_empty() {
        Ok(default
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToOwned::to_owned))
    } else {
        Ok(Some(line))
    }
}

fn prompt_yes_no(prompt: &str, default_yes: bool) -> Result<bool, CliError> {
    let suffix = if default_yes { "[Y/n]" } else { "[y/N]" };
    let line = prompt_line(&format!("{} {}: ", prompt, suffix))?;
    if line.is_empty() {
        return Ok(default_yes);
    }

    match line.to_ascii_lowercase().as_str() {
        "y" | "yes" => Ok(true),
        "n" | "no" => Ok(false),
        _ => Ok(default_yes),
    }
}

fn default_public_domain(config: &StackerConfig) -> String {
    format!(
        "{}.example.com",
        config.name.replace(' ', "-").to_ascii_lowercase()
    )
}

fn default_image_repository(state: &ScenarioState) -> String {
    state
        .vars
        .get("image_repository")
        .cloned()
        .unwrap_or_else(|| {
            let project_name = state
                .vars
                .get("project_name")
                .cloned()
                .unwrap_or_else(|| "website".to_string())
                .replace(' ', "-")
                .to_ascii_lowercase();
            format!("ghcr.io/your-org/{project_name}")
        })
}

fn default_cloud_region(provider: &str) -> &'static str {
    match provider {
        "hetzner" => "nbg1",
        "digitalocean" => "fra1",
        "linode" => "eu-central",
        "vultr" => "fra",
        "aws" => "eu-central-1",
        _ => "nbg1",
    }
}

fn default_cloud_size(provider: &str) -> &'static str {
    match provider {
        "hetzner" => "cpx11",
        "digitalocean" => "s-1vcpu-1gb",
        "linode" => "g6-nanode-1",
        "vultr" => "vc2-1c-1gb",
        "aws" => "t3.micro",
        _ => "cpx11",
    }
}

fn collect_website_scenario_inputs(
    project_dir: &Path,
    config: &StackerConfig,
    state: &mut ScenarioState,
) -> Result<(), CliError> {
    let manifest = load_scenario_manifest(project_dir, WEBSITE_DEPLOY_SCENARIO)?;

    if !state.vars.contains_key("repo_url") {
        if let Some(repo_url) = prompt_optional(
            "Git repository URL (optional, used for transcript/image hints)",
            None,
        )? {
            state.vars.insert("repo_url".to_string(), repo_url);
        }
    }

    if !state.vars.contains_key("image_repository") {
        let default_repository = default_image_repository(state);
        state
            .vars
            .entry("image_repository".to_string())
            .or_insert(default_repository);
    }

    for field in missing_required_vars(&manifest, state) {
        match field.as_str() {
            "public_domain" => {
                let value = prompt_with_default("Public domain", &default_public_domain(config))?;
                state.vars.insert(field, value);
            }
            "image_repository" => {
                let value =
                    prompt_with_default("Image repository", &default_image_repository(state))?;
                state.vars.insert(field, value);
            }
            "image_tag" => {
                let value = prompt_with_default("Image tag", "latest")?;
                state.vars.insert(field, value);
            }
            "cloud_provider" => {
                let value = prompt_with_default(
                    "Cloud provider (hetzner|digitalocean|aws|linode|vultr)",
                    "hetzner",
                )?;
                state.vars.insert(field, value);
            }
            "cloud_region" => {
                let provider = state
                    .vars
                    .get("cloud_provider")
                    .map(String::as_str)
                    .unwrap_or("hetzner");
                let value = prompt_with_default("Cloud region", default_cloud_region(provider))?;
                state.vars.insert(field, value);
            }
            "cloud_size" => {
                let provider = state
                    .vars
                    .get("cloud_provider")
                    .map(String::as_str)
                    .unwrap_or("hetzner");
                let value = prompt_with_default("Cloud size", default_cloud_size(provider))?;
                state.vars.insert(field, value);
            }
            _ => {}
        }
    }

    Ok(())
}

fn maybe_bootstrap_website_scenario(
    project_dir: &Path,
    config_path: &Path,
    config: &StackerConfig,
    ai_runtime: Option<(&AiConfig, &dyn AiProvider)>,
) -> Result<(), CliError> {
    let Some((ai_config, provider)) = ai_runtime else {
        return Ok(());
    };

    let Some(project_kind) = detect_website_project_kind(project_dir, config) else {
        return Ok(());
    };

    if !is_qwen_website_scenario_model(ai_config) {
        eprintln!(
            "💡 Website deployment scenario available for Ollama qwen2.5-code/qwen2.5-coder via `stacker ai ask \"continue\" --scenario website-deploy --step init-validate`."
        );
        return Ok(());
    }

    if !io::stdin().is_terminal() || !io::stdout().is_terminal() {
        eprintln!(
            "💡 Qwen website deployment scenario available: `stacker ai ask \"continue\" --scenario website-deploy --step init-validate`."
        );
        return Ok(());
    }

    if !prompt_yes_no(
        &format!(
            "Start the {} deployment scenario now?",
            project_kind.display_name()
        ),
        true,
    )? {
        eprintln!(
            "💡 Continue later with: `stacker ai ask \"continue\" --scenario website-deploy --step init-validate`."
        );
        return Ok(());
    }

    let mut state =
        seed_website_scenario_state(project_dir, config_path, config, ai_config, &project_kind);
    collect_website_scenario_inputs(project_dir, config, &mut state)?;
    let state_path = save_scenario_state(project_dir, &state)?;
    let selection =
        ScenarioSelection::new(WEBSITE_DEPLOY_SCENARIO, Some(state.current_step.clone()));
    let system_prompt = build_system_prompt_base(project_dir, ai_config, Some(&selection), true)?;
    let question = format!(
        "Start the {} deployment scenario at the current step. Use the saved scenario variables and current project files. Give the exact next commands, validations, and the next step only. If any required value is still missing, ask for it explicitly.",
        project_kind.display_name()
    );
    let response = run_ai_ask_with_system_prompt(&question, None, provider, &system_prompt)?;

    eprintln!("💾 Saved AI scenario state to {}", state_path.display());
    println!("\n{}", response);

    if let Some(next_step) =
        next_step_id(project_dir, WEBSITE_DEPLOY_SCENARIO, &state.current_step)?
    {
        eprintln!(
            "💡 Continue later with: `stacker ai ask \"continue\" --scenario website-deploy --step {}`.",
            next_step
        );
    }

    Ok(())
}

/// Build an `AiConfig` from CLI flags and/or environment variables.
///
/// Priority: CLI flag > environment variable > defaults.
pub fn resolve_ai_config(
    ai_provider: Option<&str>,
    ai_model: Option<&str>,
    ai_api_key: Option<&str>,
) -> Result<AiConfig, CliError> {
    // Provider: flag > env > default (ollama)
    let provider_str = ai_provider
        .map(|s| s.to_string())
        .or_else(|| std::env::var("STACKER_AI_PROVIDER").ok())
        .unwrap_or_else(|| "ollama".to_string());

    let provider = parse_ai_provider(&provider_str)?;

    // API key: flag > env (provider-specific) > env (generic) > None
    let api_key = ai_api_key
        .map(|s| s.to_string())
        .or_else(|| match provider {
            AiProviderType::Openai => std::env::var("OPENAI_API_KEY").ok(),
            AiProviderType::Anthropic => std::env::var("ANTHROPIC_API_KEY").ok(),
            _ => None,
        })
        .or_else(|| std::env::var("STACKER_AI_API_KEY").ok());

    // Model: flag > env > None (provider default will be used)
    let model = ai_model
        .map(|s| s.to_string())
        .or_else(|| std::env::var("STACKER_AI_MODEL").ok());

    // Endpoint from env
    let endpoint = std::env::var("STACKER_AI_ENDPOINT").ok();

    // Timeout: env > default (300s)
    let timeout = std::env::var("STACKER_AI_TIMEOUT")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(300);

    Ok(AiConfig {
        enabled: true,
        provider,
        model,
        api_key,
        endpoint,
        timeout,
        tasks: vec!["dockerfile".to_string(), "compose".to_string()],
    })
}

/// Parse an AI provider string into `AiProviderType`.
fn parse_ai_provider(s: &str) -> Result<AiProviderType, CliError> {
    match s.to_lowercase().as_str() {
        "openai" => Ok(AiProviderType::Openai),
        "anthropic" => Ok(AiProviderType::Anthropic),
        "ollama" => Ok(AiProviderType::Ollama),
        "custom" => Ok(AiProviderType::Custom),
        other => Err(CliError::ConfigValidation(format!(
            "Unknown AI provider '{}'. Valid: openai, anthropic, ollama, custom",
            other
        ))),
    }
}

/// Generate a `stacker.yml` config in the target directory.
///
/// This is extracted as a standalone function for testability — the
/// `InitCommand::call()` delegates here with `std::env::current_dir()`.
///
/// NOTE: This function always uses template-based generation (no network calls).
/// For AI-powered generation, use `generate_config_full()` with explicit
/// provider options — that path is invoked by the real CLI binary.
pub fn generate_config(
    project_dir: &Path,
    app_type_override: Option<&str>,
    with_proxy: bool,
    with_ai: bool,
) -> Result<PathBuf, CliError> {
    let config_path = project_dir.join(DEFAULT_CONFIG_FILE);

    if config_path.exists() {
        return Err(CliError::ConfigValidation(format!(
            "{} already exists. Remove it first or edit it directly.",
            DEFAULT_CONFIG_FILE
        )));
    }

    generate_config_template_path(
        project_dir,
        &config_path,
        app_type_override,
        with_proxy,
        with_ai,
    )
}

/// Full config generation supporting AI provider options.
pub fn generate_config_full(
    project_dir: &Path,
    app_type_override: Option<&str>,
    with_proxy: bool,
    with_ai: bool,
    ai_provider: Option<&str>,
    ai_model: Option<&str>,
    ai_api_key: Option<&str>,
) -> Result<PathBuf, CliError> {
    let config_path = project_dir.join(DEFAULT_CONFIG_FILE);

    // Don't overwrite existing config
    if config_path.exists() {
        return Err(CliError::ConfigValidation(format!(
            "{} already exists. Remove it first or edit it directly.",
            DEFAULT_CONFIG_FILE
        )));
    }

    // If --with-ai is set, try AI-powered generation
    if with_ai {
        let ai_config = resolve_ai_config(ai_provider, ai_model, ai_api_key)?;

        match create_provider(&ai_config) {
            Ok(provider) => {
                match generate_config_ai_path(
                    project_dir,
                    &config_path,
                    provider.as_ref(),
                    &ai_config,
                ) {
                    Ok(path) => return Ok(path),
                    Err(e) => {
                        eprintln!("\n⚠ AI generation failed: {}", e);
                        eprintln!("  Falling back to template-based generation.");
                        eprintln!("  Tip: make sure your Ollama model supports code generation.");
                        eprintln!("  Available models can be listed with: ollama list\n");
                    }
                }
            }
            Err(e) => {
                eprintln!("\n⚠ AI provider not available: {}", e);
                eprintln!("  Falling back to template-based generation.");
                eprintln!("  Tip: start Ollama with: ollama serve\n");
            }
        }
    }

    // Template-based generation (original flow)
    generate_config_template_path(
        project_dir,
        &config_path,
        app_type_override,
        with_proxy,
        with_ai,
    )
}

/// AI-powered config generation path.
fn generate_config_ai_path(
    project_dir: &Path,
    config_path: &Path,
    provider: &dyn AiProvider,
    ai_config: &AiConfig,
) -> Result<PathBuf, CliError> {
    eprintln!("🤖 Scanning project and generating config with AI...");

    let yaml = if ai_config.provider == AiProviderType::Ollama {
        let (system_prompt, user_prompt) = build_generation_request(project_dir);
        eprintln!("🧠 AI reasoning (streaming)...");
        let raw = ollama_complete_streaming(ai_config, &user_prompt, &system_prompt)?;
        eprintln!();
        let yaml = strip_code_fences(&raw);

        serde_yaml::from_str::<serde_yaml::Value>(&yaml).map_err(|e| {
            CliError::AiProviderError {
                provider: "ollama".to_string(),
                message: format!("AI generated invalid YAML: {}", e),
            }
        })?;

        yaml
    } else {
        generate_config_with_ai(project_dir, provider)?
    };

    // Validate it parses as StackerConfig
    match StackerConfig::from_str(&yaml) {
        Ok(_) => {}
        Err(e) => {
            // Save the raw AI output for debugging but warn
            let debug_path = project_dir.join("stacker.yml.ai-draft");
            let _ = std::fs::write(&debug_path, &yaml);
            return Err(CliError::ConfigValidation(format!(
                "AI generated a config that failed validation: {}. \
                 Raw output saved to stacker.yml.ai-draft for review.",
                e
            )));
        }
    }

    // Write with header
    let content = format!(
        "# Stacker configuration — generated by `stacker init --with-ai`\n\
         # AI provider: {} (model: {})\n\
         # Review this file and adjust as needed before deploying.\n\
         # Docs: https://docs.try.direct/stacker\n\
         \n\
         {yaml}\n\
         \n\
         {}\n",
        ai_config.provider,
        ai_config.model.as_deref().unwrap_or("default"),
        full_config_reference_example(),
    );

    std::fs::write(config_path, &content)?;

    Ok(config_path.to_path_buf())
}

/// Template-based config generation (the original flow).
fn generate_config_template_path(
    project_dir: &Path,
    config_path: &Path,
    app_type_override: Option<&str>,
    with_proxy: bool,
    with_ai: bool,
) -> Result<PathBuf, CliError> {
    let fs = RealFileSystem;
    let workspace_detection = detect_workspace(project_dir, &fs);
    let primary_app = choose_primary_app(&workspace_detection);
    let app_type = app_type_override
        .map(parse_app_type)
        .transpose()?
        .unwrap_or_else(|| {
            primary_app
                .map(|app| app.app_type)
                .unwrap_or(workspace_detection.root.app_type)
        });

    // Derive project name from directory name
    let project_name = project_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("my-app")
        .to_string();

    // Build config
    let mut builder = ConfigBuilder::new()
        .name(&project_name)
        .version("0.1.0")
        .app_type(app_type)
        .app_path(
            primary_app
                .map(|app| app.path.clone())
                .unwrap_or_else(|| PathBuf::from(".")),
        );

    if let Some(app) = primary_app {
        if let Some(dockerfile) = &app.dockerfile {
            builder = builder.app_dockerfile(dockerfile.clone());
        }
    }

    for service in importable_compose_services(&workspace_detection, primary_app) {
        builder = builder.add_service(service);
    }

    if with_proxy {
        builder = builder.proxy(ProxyConfig {
            proxy_type: ProxyType::Nginx,
            domains: vec![DomainConfig {
                domain: format!("{}.localhost", project_name),
                ssl: SslMode::Auto,
                upstream: "app:80".to_string(),
            }],
            ..ProxyConfig::default()
        });
    }

    if with_ai {
        builder = builder.ai(AiConfig {
            enabled: true,
            provider: AiProviderType::Ollama,
            ..AiConfig::default()
        });
    }

    let mut config = builder.build()?;
    if app_type_override.is_none() {
        config.deploy.compose_file = workspace_detection.recommended_compose_file.clone();
    }

    // Serialize to YAML, keeping generated configs compact and validation-clean.
    let yaml = serialize_generated_config(&config)?;

    let scan_summary = render_scan_summary(
        project_dir,
        &workspace_detection,
        primary_app,
        &project_name,
    );

    // Write with a header comment
    let content = format!(
        "# Stacker configuration — generated by `stacker init`\n\
         # Docs: https://docs.try.direct/stacker\n\
         {scan_summary}\
         \n\
         {yaml}"
    );

    std::fs::write(config_path, &content)?;

    Ok(config_path.to_path_buf())
}

fn serialize_generated_config(config: &StackerConfig) -> Result<String, CliError> {
    let mut value = serde_yaml::to_value(config)
        .map_err(|e| CliError::GeneratorError(format!("Failed to serialize config: {e}")))?;

    prune_generated_config_value(&mut value);
    remove_disabled_generated_ai_section(&mut value);

    serde_yaml::to_string(&value)
        .map_err(|e| CliError::GeneratorError(format!("Failed to serialize config: {e}")))
}

fn prune_generated_config_value(value: &mut serde_yaml::Value) {
    match value {
        serde_yaml::Value::Mapping(map) => {
            let keys = map.keys().cloned().collect::<Vec<_>>();
            for key in &keys {
                if let Some(child) = map.get_mut(key) {
                    prune_generated_config_value(child);
                }
            }

            for key in keys {
                if map.get(&key).is_some_and(is_noise_generated_config_value) {
                    map.remove(&key);
                }
            }
        }
        serde_yaml::Value::Sequence(items) => {
            for item in items.iter_mut() {
                prune_generated_config_value(item);
            }
            items.retain(|item| !is_noise_generated_config_value(item));
        }
        _ => {}
    }
}

fn is_noise_generated_config_value(value: &serde_yaml::Value) -> bool {
    match value {
        serde_yaml::Value::Null => true,
        serde_yaml::Value::Sequence(items) => items.is_empty(),
        serde_yaml::Value::Mapping(map) => map.is_empty(),
        _ => false,
    }
}

fn remove_disabled_generated_ai_section(value: &mut serde_yaml::Value) {
    let serde_yaml::Value::Mapping(root) = value else {
        return;
    };

    let ai_key = serde_yaml::Value::String("ai".to_string());
    let remove_ai = root
        .get(&ai_key)
        .and_then(serde_yaml::Value::as_mapping)
        .and_then(|ai| ai.get(serde_yaml::Value::String("enabled".to_string())))
        .and_then(serde_yaml::Value::as_bool)
        == Some(false);

    if remove_ai {
        root.remove(&ai_key);
    }
}

fn choose_primary_app(workspace_detection: &WorkspaceDetection) -> Option<&DiscoveredApp> {
    if workspace_detection.apps.is_empty() {
        return None;
    }

    if let Some(compose_file) = &workspace_detection.recommended_compose_file {
        if let Some(stack) = workspace_detection
            .compose_stacks
            .iter()
            .find(|stack| &stack.path == compose_file)
        {
            if let Some(app) = workspace_detection
                .apps
                .iter()
                .find(|app| stack.services.iter().any(|service| service == &app.name))
            {
                return Some(app);
            }
        }
    }

    workspace_detection
        .apps
        .iter()
        .find(|app| app.path == PathBuf::from("."))
        .or_else(|| {
            workspace_detection
                .apps
                .iter()
                .find(|app| app.has_dockerfile)
        })
        .or_else(|| workspace_detection.apps.first())
}

fn render_scan_summary(
    project_dir: &Path,
    workspace_detection: &WorkspaceDetection,
    primary_app: Option<&DiscoveredApp>,
    project_name: &str,
) -> String {
    let mut lines = Vec::new();

    if let Some(app) = primary_app {
        lines.push(format!(
            "# Primary app selected for generated config: {} ({})",
            app.path.display(),
            app.app_type
        ));
    } else {
        lines.push(format!(
            "# No nested app candidates detected; using root project defaults for {}",
            project_name
        ));
    }

    if !workspace_detection.apps.is_empty() {
        lines.push(format!(
            "# Discovered apps: {}",
            workspace_detection
                .apps
                .iter()
                .map(|app| format!("{} [{}]", app.path.display(), app.app_type))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    if let Some(compose_file) = &workspace_detection.recommended_compose_file {
        lines.push(format!(
            "# Reusing existing compose stack: {}",
            compose_file.display()
        ));
        if let Some(stack) = workspace_detection
            .compose_stacks
            .iter()
            .find(|stack| &stack.path == compose_file)
        {
            lines.push(format!(
                "# Compose services detected: {}",
                stack.services.join(", ")
            ));
        }
    }

    for warning in infer_bootstrap_warnings(project_dir, workspace_detection) {
        lines.push(format!("# WARNING: {}", warning));
    }

    if lines.is_empty() {
        String::new()
    } else {
        format!("{}\n", lines.join("\n"))
    }
}

fn infer_bootstrap_warnings(
    project_dir: &Path,
    workspace_detection: &WorkspaceDetection,
) -> Vec<String> {
    let Some(compose_file) = &workspace_detection.recommended_compose_file else {
        return Vec::new();
    };
    let Some(stack) = workspace_detection
        .compose_stacks
        .iter()
        .find(|stack| &stack.path == compose_file)
    else {
        return Vec::new();
    };

    workspace_detection
        .apps
        .iter()
        .filter_map(|app| {
            let service = stack
                .detected_services
                .iter()
                .find(|service| service.name == app.name)?;
            if !service_uses_properties_volume(service) {
                return None;
            }

            let app_dir = project_dir.join(&app.path);
            let private_key = app_dir.join("properties/private.pem");
            let public_key = app_dir.join("properties/public.pem");
            if private_key.exists() || public_key.exists() {
                return None;
            }

            if !tree_contains_any(
                &app_dir,
                &["properties/private.pem", "properties/public.pem"],
                6,
            ) {
                return None;
            }

            Some(format!(
                "{} mounts /app/properties but scan did not find a checked-in keypair or generator service. The app source references properties/private.pem and properties/public.pem, so bootstrap that volume before local deploy.",
                app.path.display()
            ))
        })
        .collect()
}

fn service_uses_properties_volume(service: &DetectedComposeService) -> bool {
    service.volumes.iter().any(|volume| {
        volume.contains(":/app/properties")
            || volume.ends_with(":/properties")
            || volume == "/app/properties"
            || volume.ends_with("/app/properties")
    })
}

fn tree_contains_any(base: &Path, needles: &[&str], max_depth: usize) -> bool {
    if max_depth == 0 {
        return false;
    }

    let Ok(entries) = std::fs::read_dir(base) else {
        return false;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if tree_contains_any(&path, needles, max_depth - 1) {
                return true;
            }
            continue;
        }

        let Some(extension) = path.extension().and_then(|value| value.to_str()) else {
            continue;
        };
        if !matches!(extension, "rs" | "md" | "toml" | "yml" | "yaml") {
            continue;
        }

        let Ok(contents) = std::fs::read_to_string(&path) else {
            continue;
        };
        if needles.iter().any(|needle| contents.contains(needle)) {
            return true;
        }
    }

    false
}

fn importable_compose_services(
    workspace_detection: &WorkspaceDetection,
    primary_app: Option<&DiscoveredApp>,
) -> Vec<ServiceDefinition> {
    let Some(compose_file) = &workspace_detection.recommended_compose_file else {
        return Vec::new();
    };
    let Some(stack) = workspace_detection
        .compose_stacks
        .iter()
        .find(|stack| &stack.path == compose_file)
    else {
        return Vec::new();
    };

    let primary_app_name = primary_app.map(|app| app.name.as_str());

    stack
        .detected_services
        .iter()
        .filter_map(|service| compose_service_to_definition(service, primary_app_name))
        .collect()
}

fn compose_service_to_definition(
    service: &DetectedComposeService,
    primary_app_name: Option<&str>,
) -> Option<ServiceDefinition> {
    if primary_app_name == Some(service.name.as_str()) {
        return None;
    }

    Some(ServiceDefinition {
        name: service.name.clone(),
        image: normalize_compose_string(&service.image.clone()?)?,
        ports: service
            .ports
            .iter()
            .filter_map(|value| normalize_compose_string(value))
            .collect(),
        environment: service
            .environment
            .iter()
            .filter_map(|(key, value)| Some((key.clone(), normalize_compose_string(value)?)))
            .collect(),
        volumes: service
            .volumes
            .iter()
            .filter_map(|value| normalize_compose_string(value))
            .collect(),
        depends_on: service.depends_on.clone(),
    })
}

fn normalize_compose_string(value: &str) -> Option<String> {
    let pattern = regex::Regex::new(r"\$\{([^}:?+-]+)(?:(:?[-?+])([^}]*))?\}").ok()?;
    let mut normalized = value.to_string();

    for capture in pattern.captures_iter(value) {
        let full_match = capture.get(0)?.as_str();
        let var_name = capture.get(1)?.as_str();
        let operator = capture.get(2).map(|matched| matched.as_str());
        let operand = capture.get(3).map(|matched| matched.as_str()).unwrap_or("");

        let replacement = match operator {
            None => full_match.to_string(),
            Some(":-") | Some("-") => operand.to_string(),
            Some(":?") | Some("?") => continue,
            Some(":+") | Some("+") => operand.to_string(),
            _ => var_name.to_string(),
        };

        normalized = normalized.replace(full_match, &replacement);
    }

    Some(normalized)
}

/// Output directory for generated artifacts.
const OUTPUT_DIR: &str = ".stacker";

fn summarize_top_level_entries(project_dir: &Path, limit: usize) -> String {
    let mut entries: Vec<String> = match std::fs::read_dir(project_dir) {
        Ok(iter) => iter
            .filter_map(|item| item.ok())
            .filter_map(|entry| entry.file_name().into_string().ok())
            .collect(),
        Err(_) => return "(unable to read project directory)".to_string(),
    };

    entries.sort();
    if entries.len() > limit {
        entries.truncate(limit);
    }

    if entries.is_empty() {
        "(empty directory)".to_string()
    } else {
        entries.join(", ")
    }
}

fn collect_generation_context(project_dir: &Path, config: &StackerConfig) -> Vec<String> {
    let mut context = Vec::new();

    let config_yaml = serde_yaml::to_string(config)
        .unwrap_or_else(|_| "(failed to serialize stacker.yml context)".to_string());

    context.push(format!("Project path: {}", project_dir.display()));
    context.push(format!("Detected app type: {}", config.app.app_type));
    context.push(format!(
        "Top-level project entries: {}",
        summarize_top_level_entries(project_dir, 50)
    ));
    context.push(format!("stacker.yml:\n{}", config_yaml));

    let package_json_path = project_dir.join("package.json");
    if let Ok(package_json) = std::fs::read_to_string(&package_json_path) {
        context.push(format!("package.json:\n{}", package_json));

        if let Ok(pkg_json) = serde_json::from_str::<serde_json::Value>(&package_json) {
            if let Some(scripts) = pkg_json.get("scripts") {
                context.push(format!("Detected package.json scripts: {}", scripts));
            }
            if let Some(main) = pkg_json.get("main").and_then(|v| v.as_str()) {
                context.push(format!("Detected package.json main entry: {}", main));
            }
            if let Some(module) = pkg_json.get("module").and_then(|v| v.as_str()) {
                context.push(format!("Detected package.json module entry: {}", module));
            }
        }
    }

    let pyproject_path = project_dir.join("pyproject.toml");
    if let Ok(pyproject) = std::fs::read_to_string(&pyproject_path) {
        context.push(format!("pyproject.toml:\n{}", pyproject));
    }

    let requirements_path = project_dir.join("requirements.txt");
    if let Ok(requirements) = std::fs::read_to_string(&requirements_path) {
        context.push(format!("requirements.txt:\n{}", requirements));
    }

    let candidate_entries = [
        "server.js",
        "app.js",
        "index.js",
        "main.js",
        "dist/index.js",
        "dist/server.js",
        "src/main.rs",
        "main.py",
    ];

    let existing_entries: Vec<&str> = candidate_entries
        .iter()
        .copied()
        .filter(|path| project_dir.join(path).exists())
        .collect();

    context.push(format!(
        "Known entrypoint candidates found: {}",
        if existing_entries.is_empty() {
            "(none)".to_string()
        } else {
            existing_entries.join(", ")
        }
    ));

    let lockfiles = [
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "Cargo.lock",
    ];
    let found_lockfiles: Vec<&str> = lockfiles
        .iter()
        .copied()
        .filter(|file| project_dir.join(file).exists())
        .collect();
    if !found_lockfiles.is_empty() {
        context.push(format!(
            "Detected lockfiles: {}",
            found_lockfiles.join(", ")
        ));
    }

    context
}

fn generate_dockerfile_with_ai(
    project_dir: &Path,
    config: &StackerConfig,
    ai_config: &AiConfig,
    provider: &dyn AiProvider,
) -> Result<String, CliError> {
    let context = collect_generation_context(project_dir, config);

    let prompt = format!(
        "Generate a production-ready Dockerfile for this project.\n\n{}\n\nRequirements:\n- Output ONLY Dockerfile text, no markdown fences or explanation.\n- The Dockerfile must be runnable for the detected app type.\n- Prefer startup commands that exist in project metadata (e.g., package.json scripts).\n- Do NOT reference files unless they exist in the provided context.\n- Avoid placeholder commands (like hardcoded server.js) unless that file is explicitly present.\n- Expose the correct application port.\n- Keep the build deterministic and cache-friendly (copy lockfiles first where applicable).",
        context.join("\n\n")
    );

    let system = "You are an expert Docker engineer. Return only valid Dockerfile content.";
    let raw = if ai_config.provider == AiProviderType::Ollama {
        eprintln!("🧠 AI reasoning for Dockerfile (streaming)...");
        let response = ollama_complete_streaming(ai_config, &prompt, system)?;
        eprintln!();
        response
    } else {
        provider.complete(&prompt, system)?
    };
    let dockerfile = strip_code_fences(&raw);

    if !dockerfile
        .lines()
        .any(|line| line.trim_start().starts_with("FROM "))
    {
        return Err(CliError::GeneratorError(
            "AI generated Dockerfile without a FROM instruction".to_string(),
        ));
    }

    Ok(dockerfile)
}

fn generate_compose_with_ai(
    project_dir: &Path,
    config: &StackerConfig,
    dockerfile_path: &Path,
    ai_config: &AiConfig,
    provider: &dyn AiProvider,
) -> Result<String, CliError> {
    let context = collect_generation_context(project_dir, config);

    let dockerfile_rel = dockerfile_path
        .strip_prefix(project_dir)
        .unwrap_or(dockerfile_path)
        .to_string_lossy()
        .to_string();

    let prompt = format!(
        "Generate a docker compose YAML file for this project.\n\n{}\n\nRequirements:\n- Output ONLY YAML, no markdown fences or explanation.\n- Include a top-level 'services' map.\n- The compose file will be written under `.stacker/`, so for the main app service set build context to `..` and dockerfile to '{}'.\n- Do NOT use build context '.' when dockerfile points to `.stacker/` because Docker would miss project files.\n- Include ports based on app type and include sidecar services from stacker.yml where relevant.\n- Keep the file compatible with `docker compose` (plugin).",
        context.join("\n\n"), dockerfile_rel
    );

    let system =
        "You are an expert Docker Compose engineer. Return only valid docker compose YAML.";
    let raw = if ai_config.provider == AiProviderType::Ollama {
        eprintln!("🧠 AI reasoning for compose (streaming)...");
        let response = ollama_complete_streaming(ai_config, &prompt, system)?;
        eprintln!();
        response
    } else {
        provider.complete(&prompt, system)?
    };
    let compose = strip_code_fences(&raw);

    let parsed: serde_yaml::Value = serde_yaml::from_str(&compose)
        .map_err(|e| CliError::GeneratorError(format!("AI generated invalid compose YAML: {e}")))?;

    if parsed.get("services").is_none() {
        return Err(CliError::GeneratorError(
            "AI generated compose YAML without top-level 'services'".to_string(),
        ));
    }

    Ok(compose)
}

impl CallableTrait for InitCommand {
    fn call(&self) -> Result<(), Box<dyn std::error::Error>> {
        let project_dir = std::env::current_dir()?;

        let config_path = generate_config_full(
            &project_dir,
            self.app_type.as_deref(),
            self.with_proxy,
            self.with_ai,
            self.ai_provider.as_deref(),
            self.ai_model.as_deref(),
            self.ai_api_key.as_deref(),
        )?;

        eprintln!("✓ Created {}", config_path.display());

        if self.with_cloud {
            eprintln!("☁ Running cloud setup wizard...");
            let path_str = config_path.to_string_lossy().to_string();
            let applied =
                crate::console::commands::cli::config::run_setup_cloud_interactive(&path_str)?;
            for item in applied {
                eprintln!("  - {}", item);
            }
        }

        // Verify the generated file is parseable
        let config = StackerConfig::from_file(&config_path)?;
        eprintln!("  Project: {} ({})", config.name, config.app.app_type);

        if self.with_proxy || config.proxy.proxy_type != ProxyType::None {
            eprintln!("  Proxy: enabled ({})", config.proxy.proxy_type);
        }
        if config.ai.enabled {
            eprintln!("  AI: enabled ({})", config.ai.provider);
        }
        if !config.services.is_empty() {
            eprintln!(
                "  Services: {}",
                config
                    .services
                    .iter()
                    .map(|s| s.name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }

        // Generate .stacker/ directory with Dockerfile and docker-compose.yml
        let output_dir = project_dir.join(OUTPUT_DIR);
        std::fs::create_dir_all(&output_dir)?;

        // Optional AI provider for artifact generation
        let ai_runtime = if self.with_ai {
            match resolve_ai_config(
                self.ai_provider.as_deref(),
                self.ai_model.as_deref(),
                self.ai_api_key.as_deref(),
            ) {
                Ok(ai_cfg) => match create_provider(&ai_cfg) {
                    Ok(provider) => Some((ai_cfg, provider)),
                    Err(e) => {
                        eprintln!("⚠ AI artifact generation unavailable: {}", e);
                        None
                    }
                },
                Err(e) => {
                    eprintln!("⚠ AI artifact generation unavailable: {}", e);
                    None
                }
            }
        } else {
            None
        };

        // Generate Dockerfile
        let needs_dockerfile = config.app.image.is_none() && config.app.dockerfile.is_none();
        if self.with_ai {
            let dockerfile_path = output_dir.join("Dockerfile");
            let mut generated = false;

            if let Some((ref ai_cfg, ref provider)) = ai_runtime {
                match generate_dockerfile_with_ai(&project_dir, &config, ai_cfg, provider.as_ref())
                {
                    Ok(dockerfile) => {
                        std::fs::write(&dockerfile_path, dockerfile)?;
                        eprintln!("✓ Generated {}/Dockerfile (AI)", OUTPUT_DIR);
                        generated = true;
                    }
                    Err(e) => {
                        eprintln!("⚠ AI Dockerfile generation failed: {}", e);
                        eprintln!("  Falling back to template Dockerfile generation.");
                    }
                }
            }

            if !generated {
                let builder = DockerfileBuilder::for_project(&project_dir, config.app.app_type);
                builder.write_to(&dockerfile_path, true)?;
                eprintln!("✓ Regenerated {}/Dockerfile (template)", OUTPUT_DIR);
            }
        } else if needs_dockerfile {
            let dockerfile_path = output_dir.join("Dockerfile");
            let builder = DockerfileBuilder::for_project(&project_dir, config.app.app_type);
            builder.write_to(&dockerfile_path, false)?;
            eprintln!("✓ Generated {}/Dockerfile", OUTPUT_DIR);
        }

        // Generate docker-compose.yml
        if self.with_ai {
            let compose_path = output_dir.join("docker-compose.yml");
            let dockerfile_path = output_dir.join("Dockerfile");
            let mut generated = false;

            if let Some((ref ai_cfg, ref provider)) = ai_runtime {
                match generate_compose_with_ai(
                    &project_dir,
                    &config,
                    &dockerfile_path,
                    ai_cfg,
                    provider.as_ref(),
                ) {
                    Ok(compose_yaml) => {
                        std::fs::write(&compose_path, compose_yaml)?;
                        eprintln!("✓ Generated {}/docker-compose.yml (AI)", OUTPUT_DIR);
                        generated = true;
                    }
                    Err(e) => {
                        eprintln!("⚠ AI compose generation failed: {}", e);
                        eprintln!("  Falling back to template compose generation.");
                    }
                }
            }

            if !generated {
                let compose = ComposeDefinition::try_from(&config)?;
                compose.write_to(&compose_path, true)?;
                eprintln!("✓ Regenerated {}/docker-compose.yml (template)", OUTPUT_DIR);
            }
        } else if config.deploy.compose_file.is_none() {
            let compose_path = output_dir.join("docker-compose.yml");
            let compose = ComposeDefinition::try_from(&config)?;
            compose.write_to(&compose_path, false)?;
            eprintln!("✓ Generated {}/docker-compose.yml", OUTPUT_DIR);
        }

        eprintln!("\nNext steps:");
        eprintln!("  stacker config validate   # Check configuration");
        eprintln!("  stacker deploy --target local --dry-run   # Preview deployment");
        eprintln!("  stacker deploy --target local   # Deploy locally");

        if self.with_ai {
            maybe_bootstrap_website_scenario(
                &project_dir,
                &config_path,
                &config,
                ai_runtime
                    .as_ref()
                    .map(|(cfg, provider)| (cfg, provider.as_ref())),
            )?;
        }

        Ok(())
    }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Tests
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    struct MockAiProvider {
        responses: std::sync::Mutex<std::collections::VecDeque<String>>,
    }

    impl MockAiProvider {
        fn new(responses: Vec<&str>) -> Self {
            Self {
                responses: std::sync::Mutex::new(
                    responses.into_iter().map(|s| s.to_string()).collect(),
                ),
            }
        }
    }

    impl AiProvider for MockAiProvider {
        fn name(&self) -> &str {
            "mock"
        }

        fn complete(&self, _prompt: &str, _context: &str) -> Result<String, CliError> {
            let mut queue = self.responses.lock().unwrap();
            if let Some(next) = queue.pop_front() {
                return Ok(next);
            }

            Err(CliError::AiProviderError {
                provider: "mock".to_string(),
                message: "No mock response configured".to_string(),
            })
        }
    }

    fn setup_dir_with_files(files: &[&str]) -> TempDir {
        let dir = TempDir::new().unwrap();
        for f in files {
            std::fs::write(dir.path().join(f), "").unwrap();
        }
        dir
    }

    fn setup_dir_with_nested_files(files: &[(&str, &str)]) -> TempDir {
        let dir = TempDir::new().unwrap();
        for (path, content) in files {
            let file_path = dir.path().join(path);
            if let Some(parent) = file_path.parent() {
                std::fs::create_dir_all(parent).unwrap();
            }
            std::fs::write(file_path, content).unwrap();
        }
        dir
    }

    #[test]
    fn test_init_static_project_creates_config() {
        let dir = setup_dir_with_files(&["index.html"]);
        let result = generate_config(dir.path(), None, false, false);
        assert!(result.is_ok());

        let path = result.unwrap();
        assert!(path.exists());

        let config = StackerConfig::from_file(&path).unwrap();
        assert_eq!(config.app.app_type, AppType::Static);
    }

    #[test]
    fn test_init_node_project_detects_correctly() {
        let dir = setup_dir_with_files(&["package.json"]);
        let result = generate_config(dir.path(), None, false, false);
        assert!(result.is_ok());

        let config = StackerConfig::from_file(&result.unwrap()).unwrap();
        assert_eq!(config.app.app_type, AppType::Node);
    }

    #[test]
    fn test_init_type_flag_overrides_detection() {
        // Dir has package.json (Node) but flag says python
        let dir = setup_dir_with_files(&["package.json"]);
        let result = generate_config(dir.path(), Some("python"), false, false);
        assert!(result.is_ok());

        let config = StackerConfig::from_file(&result.unwrap()).unwrap();
        assert_eq!(config.app.app_type, AppType::Python);
    }

    #[test]
    fn test_init_with_proxy_flag_adds_section() {
        let dir = setup_dir_with_files(&["index.html"]);
        let result = generate_config(dir.path(), None, true, false);
        assert!(result.is_ok());

        let config = StackerConfig::from_file(&result.unwrap()).unwrap();
        assert_eq!(config.proxy.proxy_type, ProxyType::Nginx);
        assert!(!config.proxy.domains.is_empty());
        assert!(config.proxy.domains[0].domain.contains("localhost"));
    }

    #[test]
    fn test_init_with_ai_flag_adds_section() {
        let dir = setup_dir_with_files(&["index.html"]);
        let result = generate_config(dir.path(), None, false, true);
        assert!(result.is_ok());

        let config = StackerConfig::from_file(&result.unwrap()).unwrap();
        assert!(config.ai.enabled);
        assert_eq!(config.ai.provider, AiProviderType::Ollama);
    }

    #[test]
    fn test_init_does_not_overwrite_existing() {
        let dir = setup_dir_with_files(&["index.html", DEFAULT_CONFIG_FILE]);
        let result = generate_config(dir.path(), None, false, false);
        assert!(result.is_err());

        let err = format!("{}", result.unwrap_err());
        assert!(err.contains("already exists"));
    }

    #[test]
    fn test_init_output_parses_as_valid_config() {
        let dir = setup_dir_with_files(&["index.html"]);
        let path = generate_config(dir.path(), None, false, false).unwrap();

        // Must be parseable
        let result = StackerConfig::from_file(&path);
        assert!(result.is_ok());
    }

    #[test]
    fn test_init_output_from_compose_validates_without_empty_path_noise() {
        let dir = setup_dir_with_nested_files(&[
            ("package.json", r#"{"name":"web","version":"0.1.0"}"#),
            (
                "docker-compose.yml",
                "services:\n  status-panel-web:\n    image: trydirect/status-panel-web:latest\n    ports:\n      - \"3000:3000\"\n    environment:\n      NEXT_PUBLIC_SITE_URL: https://status.stacker.my\n      INTENTIONAL_EMPTY: null\n      NODE_ENV: production\n",
            ),
        ]);
        let path = generate_config(dir.path(), None, false, false).unwrap();
        let rendered = std::fs::read_to_string(&path).unwrap();
        let issues =
            crate::console::commands::cli::config::run_validate(&path.to_string_lossy()).unwrap();

        assert_eq!(issues, Vec::<String>::new());
        assert!(rendered.contains("target: local"));
        assert!(rendered.contains("type: none"));
        assert!(rendered.contains("status_panel: false"));
        assert!(rendered.contains("INTENTIONAL_EMPTY: ''"));
        assert!(!rendered.contains(": null"));
        assert!(!rendered.contains("dockerfile:"));
        assert!(!rendered.contains("env_file:"));
        assert!(!rendered.contains("hooks:"));
        assert!(!rendered.contains("ports: []"));
        assert!(!rendered.contains("environment: {}"));
        assert!(!rendered.contains("depends_on: []"));
    }

    #[test]
    fn test_init_empty_dir_defaults_to_custom() {
        let dir = TempDir::new().unwrap();
        let result = generate_config(dir.path(), None, false, false);
        assert!(result.is_ok());

        let config = StackerConfig::from_file(&result.unwrap()).unwrap();
        // Empty dir with no recognized files → Custom (detector default)
        assert_eq!(config.app.app_type, AppType::Custom);
    }

    #[test]
    fn test_init_monorepo_reuses_existing_compose_stack() {
        let dir = setup_dir_with_nested_files(&[
            ("device-api/Cargo.toml", "[package]\nname = \"device-api\"\nversion = \"0.1.0\"\n"),
            ("device-api/Dockerfile", "FROM rust:1.82\n"),
            (
                "device-api/src/auth/jwt.rs",
                "const PRIVATE_KEY_PATH: &str = \"properties/private.pem\";\nconst PUBLIC_KEY_PATH: &str = \"properties/public.pem\";\n",
            ),
            ("upload/Cargo.toml", "[package]\nname = \"upload\"\nversion = \"0.1.0\"\n"),
            ("upload/Dockerfile", "FROM rust:1.82\n"),
            (
                "docker/local/compose.yml",
                "include:\n  - ../../device-api/docker/local/compose.yml\n  - ../../upload/docker/local/compose.yml\n",
            ),
            (
                "device-api/docker/local/compose.yml",
                "services:\n  device-api:\n    build: .\n    volumes:\n      - device-api-properties:/app/properties\n",
            ),
            (
                "upload/docker/local/compose.yml",
                "services:\n  upload:\n    build: .\n    image: ${UPLOAD_IMAGE:-upload:local}\n    ports:\n      - \"8080:8080\"\n  redis:\n    image: redis:7\n  grafana:\n    image: grafana/grafana:latest\n    environment:\n      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin123}\n",
            ),
        ]);

        let path = generate_config(dir.path(), None, false, false).unwrap();
        let config = StackerConfig::from_file(&path).unwrap();
        let rendered = std::fs::read_to_string(&path).unwrap();

        assert_eq!(config.app.path, PathBuf::from("device-api"));
        assert_eq!(
            config.app.dockerfile,
            Some(PathBuf::from("device-api/Dockerfile"))
        );
        assert_eq!(
            config.deploy.compose_file,
            Some(PathBuf::from("docker/local/compose.yml"))
        );
        let mut service_names = config
            .services
            .iter()
            .map(|service| service.name.as_str())
            .collect::<Vec<_>>();
        service_names.sort();
        assert_eq!(service_names, vec!["grafana", "redis", "upload"]);
        let upload = config
            .services
            .iter()
            .find(|service| service.name == "upload")
            .unwrap();
        assert_eq!(upload.image, "upload:local");
        assert_eq!(upload.ports, vec!["8080:8080"]);
        let grafana = config
            .services
            .iter()
            .find(|service| service.name == "grafana")
            .unwrap();
        assert_eq!(
            grafana
                .environment
                .get("GF_SECURITY_ADMIN_PASSWORD")
                .map(|value| value.as_str()),
            Some("admin123")
        );
        assert!(rendered.contains("Discovered apps: device-api [custom], upload [custom]"));
        assert!(rendered.contains("Compose services detected: device-api, grafana, redis, upload"));
        assert!(rendered.contains("device-api mounts /app/properties but scan did not find a checked-in keypair or generator service"));
    }

    #[test]
    fn test_parse_app_type_valid() {
        assert_eq!(parse_app_type("static").unwrap(), AppType::Static);
        assert_eq!(parse_app_type("node").unwrap(), AppType::Node);
        assert_eq!(parse_app_type("Python").unwrap(), AppType::Python);
        assert_eq!(parse_app_type("RUST").unwrap(), AppType::Rust);
    }

    #[test]
    fn test_parse_app_type_invalid() {
        let result = parse_app_type("java");
        assert!(result.is_err());
        let err = format!("{}", result.unwrap_err());
        assert!(err.contains("Unknown app type"));
    }

    // ── AI provider resolution tests ────────────────

    static AI_CONFIG_ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn clear_ai_config_env() {
        std::env::remove_var("STACKER_AI_PROVIDER");
        std::env::remove_var("OPENAI_API_KEY");
        std::env::remove_var("ANTHROPIC_API_KEY");
        std::env::remove_var("STACKER_AI_MODEL");
        std::env::remove_var("STACKER_AI_API_KEY");
        std::env::remove_var("STACKER_AI_ENDPOINT");
        std::env::remove_var("STACKER_AI_TIMEOUT");
    }

    #[test]
    fn test_resolve_ai_config_defaults_to_ollama() {
        let _guard = AI_CONFIG_ENV_LOCK.lock().unwrap();
        clear_ai_config_env();

        let config = resolve_ai_config(None, None, None).unwrap();
        assert!(config.enabled);
        assert_eq!(config.provider, AiProviderType::Ollama);
        assert!(config.api_key.is_none());
    }

    #[test]
    fn test_resolve_ai_config_explicit_provider() {
        let config = resolve_ai_config(
            Some("anthropic"),
            Some("claude-sonnet-4-20250514"),
            Some("sk-ant-test"),
        )
        .unwrap();
        assert_eq!(config.provider, AiProviderType::Anthropic);
        assert_eq!(config.model.as_deref(), Some("claude-sonnet-4-20250514"));
        assert_eq!(config.api_key.as_deref(), Some("sk-ant-test"));
    }

    #[test]
    fn test_resolve_ai_config_openai_with_key() {
        let config = resolve_ai_config(Some("openai"), None, Some("sk-test123")).unwrap();
        assert_eq!(config.provider, AiProviderType::Openai);
        assert_eq!(config.api_key.as_deref(), Some("sk-test123"));
    }

    #[test]
    fn test_resolve_ai_config_invalid_provider_errors() {
        let result = resolve_ai_config(Some("invalid-provider"), None, None);
        assert!(result.is_err());
        let err = format!("{}", result.unwrap_err());
        assert!(err.contains("Unknown AI provider"));
    }

    #[test]
    fn test_resolve_ai_config_env_var_fallback() {
        let _guard = AI_CONFIG_ENV_LOCK.lock().unwrap();
        clear_ai_config_env();

        std::env::set_var("STACKER_AI_PROVIDER", "openai");
        std::env::set_var("OPENAI_API_KEY", "sk-from-env");
        std::env::set_var("STACKER_AI_MODEL", "gpt-4o-mini");

        let config = resolve_ai_config(None, None, None).unwrap();
        assert_eq!(config.provider, AiProviderType::Openai);
        assert_eq!(config.api_key.as_deref(), Some("sk-from-env"));
        assert_eq!(config.model.as_deref(), Some("gpt-4o-mini"));

        clear_ai_config_env();
    }

    #[test]
    fn test_resolve_ai_config_flag_overrides_env() {
        let _guard = AI_CONFIG_ENV_LOCK.lock().unwrap();
        clear_ai_config_env();

        std::env::set_var("STACKER_AI_PROVIDER", "openai");

        // Flag says ollama, env says openai — flag wins
        let config = resolve_ai_config(Some("ollama"), None, None).unwrap();
        assert_eq!(config.provider, AiProviderType::Ollama);

        clear_ai_config_env();
    }

    #[test]
    fn test_resolve_ai_config_timeout_default() {
        let _guard = AI_CONFIG_ENV_LOCK.lock().unwrap();
        clear_ai_config_env();

        let config = resolve_ai_config(None, None, None).unwrap();
        assert_eq!(config.timeout, 300);
    }

    #[test]
    fn test_resolve_ai_config_timeout_from_env() {
        let _guard = AI_CONFIG_ENV_LOCK.lock().unwrap();
        clear_ai_config_env();

        std::env::set_var("STACKER_AI_TIMEOUT", "900");
        let config = resolve_ai_config(None, None, None).unwrap();
        assert_eq!(config.timeout, 900);
        clear_ai_config_env();
    }

    #[test]
    fn test_parse_ai_provider_all_valid() {
        assert_eq!(parse_ai_provider("openai").unwrap(), AiProviderType::Openai);
        assert_eq!(
            parse_ai_provider("anthropic").unwrap(),
            AiProviderType::Anthropic
        );
        assert_eq!(parse_ai_provider("ollama").unwrap(), AiProviderType::Ollama);
        assert_eq!(parse_ai_provider("custom").unwrap(), AiProviderType::Custom);
        // Case insensitive
        assert_eq!(parse_ai_provider("OpenAI").unwrap(), AiProviderType::Openai);
        assert_eq!(
            parse_ai_provider("ANTHROPIC").unwrap(),
            AiProviderType::Anthropic
        );
    }

    #[test]
    fn test_generate_config_full_template_fallback() {
        // with_ai=true but bogus provider → create_provider fails → falls back to template
        let dir = setup_dir_with_files(&["package.json"]);
        // Use an explicit provider that will fail connection (port 1 is unreachable)
        // This avoids hitting a real running Ollama instance
        let result = generate_config_full(
            dir.path(),
            None,
            false,
            true,
            Some("custom"),
            None,
            Some("fake-key"),
        );
        assert!(result.is_ok());

        let config = StackerConfig::from_file(&result.unwrap()).unwrap();
        // Template fallback still generates correct app type
        assert_eq!(config.app.app_type, AppType::Node);
        // And includes AI section in config
        assert!(config.ai.enabled);
    }

    #[test]
    fn test_generate_dockerfile_with_ai_strips_fences() {
        let dir = setup_dir_with_files(&["package.json"]);
        let config = ConfigBuilder::new()
            .name("demo")
            .version("0.1.0")
            .app_type(AppType::Node)
            .app_path(".")
            .build()
            .unwrap();

        let provider = MockAiProvider::new(vec![
            "```dockerfile\nFROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY . .\nCMD [\"npm\",\"start\"]\n```",
        ]);

        let ai_cfg = AiConfig {
            enabled: true,
            provider: AiProviderType::Custom,
            ..AiConfig::default()
        };

        let dockerfile =
            generate_dockerfile_with_ai(dir.path(), &config, &ai_cfg, &provider).unwrap();
        assert!(dockerfile.contains("FROM node:20-alpine"));
        assert!(!dockerfile.contains("```"));
    }

    #[test]
    fn test_generate_compose_with_ai_validates_services_key() {
        let dir = setup_dir_with_files(&[]);
        let config = ConfigBuilder::new()
            .name("demo")
            .version("0.1.0")
            .app_type(AppType::Node)
            .app_path(".")
            .build()
            .unwrap();

        let provider = MockAiProvider::new(vec![
            "services:\n  app:\n    build:\n      context: .\n      dockerfile: .stacker/Dockerfile\n    ports:\n      - \"3000:3000\"\n",
        ]);

        let ai_cfg = AiConfig {
            enabled: true,
            provider: AiProviderType::Custom,
            ..AiConfig::default()
        };

        let compose = generate_compose_with_ai(
            dir.path(),
            &config,
            &dir.path().join(".stacker").join("Dockerfile"),
            &ai_cfg,
            &provider,
        )
        .unwrap();

        assert!(compose.contains("services:"));
        assert!(compose.contains("dockerfile: .stacker/Dockerfile"));
    }
}
